version: "3.7"

services:
  nginx:
    build: ./nginx
    container_name: nginx
    image: web-server
    environment:
      - DOMAIN=${DOMAIN}
    command: tail -f /dev/null
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./site:/var/www/${DOMAIN}
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    depends_on:
      - nginx
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
volumes:
  certbot_conf:
  certbot_www:
